BaseRomInputDirectory: C:/Users/Alex/Downloads/Crystal-Rand/Crystal-Rand-2
BaseRomOutputDirectory: C:/Users/Alex/Downloads/Crystal-Rand/Crystal-Rand-2
DefaultSettings: C:/Users/Alex/Development/Pokemon-Crystal-Item-Randomizer/Modes/WarpKeyTM.yml
